version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      build-deps:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /src
    schedule:
      interval: weekly
