version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /archisteamfarm
    target-branch: dev
    schedule:
      interval: daily
