name: ArchiSteamFarm
version: "1.1"
slug: archisteamfarm
description: C# application with primary purpose of farming Steam cards from multiple accounts simultaneously
url: https://github.com/Eskander/ha-addon-archisteamfarm
image: ghcr.io/eskander/ha-addon-archisteamfarm-{arch}
codenotary: mail@eskander.tn
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 1242
panel_icon: mdi:steam
ports:
  1242/tcp: null
map:
  - addon_config:rw
