name: Dependabot Auto-Merge

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'

concurrency:
  group: dependabot
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Merge Dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve ${{github.event.pull_request.html_url}}
          gh pr edit --add-label "auto-merged" "${{ github.event.pull_request.html_url }}"
          gh pr merge --merge "${{ github.event.pull_request.html_url }}"
