name: Create Release PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/Dockerfile'

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    name: Prepare dependency metadata
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.extract-metadata.outputs.dependency-names }}
      package_version: ${{ steps.get-version.outputs.package_version }}
    steps:
      - name: Fetch dependency metadata
        id: extract-metadata
        uses: dependabot/fetch-metadata@v2.2.0
        
      - name: Get package version
        id: get-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.extract-metadata.outputs.new-version }}"
          
          if [ "$VERSION" = "" ]; then
            REPO_NAME="${{ steps.extract-metadata.outputs.dependency-names }}"
            VERSION=$(gh api repos/$REPO_NAME/releases/latest --jq .tag_name)
          fi
          
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT

  merge-base:
    name: Upgrade base package
    uses: ./.github/workflows/auto-merge.yml

  bump-version:
    name: Bump version and changelog
    needs: [metadata, merge-base]
    runs-on: ubuntu-latest
    outputs:
      addon_version: ${{ steps.bump.outputs.addon_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: main

      - name: Extract and update version
        id: bump
        run: |
          # Extract current version from config.yaml
          CURRENT_VERSION=$(grep "version:" src/config.yaml | sed 's/.*: "\(.*\)"/\1/')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Calculate new addon version (bump minor)
          MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
          MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
          NEW_MINOR=$((MINOR + 1))
          ADDON_VERSION="$MAJOR.$NEW_MINOR"
          echo "addon_version=$ADDON_VERSION" >> $GITHUB_OUTPUT
          
          # Update config.yaml with the new addon version
          sed -i "s/version: .*/version: \"$ADDON_VERSION\"/" src/config.yaml
          
          # Update CHANGELOG.md
          NEW_ENTRY="# $ADDON_VERSION\n- Update ${{ needs.metadata.outputs.package_name }} to ${{ needs.metadata.outputs.package_version }}\n"
          echo -e "$NEW_ENTRY$(cat src/CHANGELOG.md)" > src/CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/config.yaml src/CHANGELOG.md
          git commit -m "Bump version to ${{ steps.bump.outputs.addon_version }}"
          git push

  create-release-pr:
    name: Create pull request
    needs: [metadata, bump-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          fetch-depth: 0

      - name: Get commit list
        id: get-commits
        run: |
          # Fetch release branch
          git fetch origin release:release --no-tags
          
          # Get the last commit that was merged to release
          LAST_RELEASE_COMMIT=$(git merge-base main release)
          
          # Get all commits between last release and current main
          COMMITS=$(git log --pretty=format:"- %s (%h)" $LAST_RELEASE_COMMIT..main)
          
          # Properly handle multiline output for GitHub Actions
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "commits<<$EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create pull request
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY=$(cat <<EOF
          ## Automated Release Update
          
          ### Version: ${{ needs.bump-version.outputs.addon_version }}
          
          ### Dependency Updates
          - Package: ${{ needs.metadata.outputs.package_name }}
          - Updated Version: ${{ needs.metadata.outputs.package_version }}
          
          ### Commits
          ${{ steps.get-commits.outputs.commits }}
          EOF
          )
          
          gh pr create \
            --base release \
            --head main \
            --title "Release: ${{ needs.bump-version.outputs.addon_version }}" \
            --body "$PR_BODY" \
            --reviewer "Eskander" \
            --assignee "Eskander" \
            --label "release"
