name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  version-bump:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'justarchinet/archisteamfarm')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Extract current version and PR title
        id: extract
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Extract current version from config.yaml
          CURRENT_VERSION=$(grep "version:" src/config.yaml | sed 's/.*: "\(.*\)"/\1/')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Calculate new version (bump minor)
          MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
          MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Clean PR title (remove backticks and "in /src")
          CLEAN_TITLE=$(echo "$PR_TITLE" | sed 's/`//g' | sed 's/ in \/src$//')
          echo "pr_title=${CLEAN_TITLE}" >> $GITHUB_OUTPUT

      - name: Update version in config.yaml
        run: |
          sed -i 's/version: ".*"/version: "${{ steps.extract.outputs.new_version }}"/' src/config.yaml

      - name: Update CHANGELOG.md
        run: |
          # Prepare new entry
          NEW_ENTRY="# ${{ steps.extract.outputs.new_version }}\n- ${{ steps.extract.outputs.pr_title }}\n"
          
          # Prepend new entry to CHANGELOG.md
          echo -e "$NEW_ENTRY$(cat src/CHANGELOG.md)" > src/CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/config.yaml src/CHANGELOG.md
          git commit -m "Bump version to ${{ steps.extract.outputs.new_version }}"
          git push
